In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('cars.csv')

In [5]:
df.head()

,id_x,car_rel_url_x,datetime_scrape,name,price_x,currency_x,datetime_product,city,day,hour,...,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Yürüş,Ötürücü,Şəhər,car_details_id_y,car_rel_url,extra_info
0,3c234145-d57a-4ad6-9448-d43810fc3392,/autos/8748840-hyundai-i30,2024-09-13 20:32:19.751157+00,Hyundai i30,15000.0,AZN,"Bakı, dünən 23:28",bakı,13.09.2024,23:28,...,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,5,270 000 km,Ön,Bakı,8d84d800-fafd-4d5c-b640-f47bd6c5ac20,/autos/8748840-hyundai-i30,Yüngül lehimli disklər* ABS* Mərkəzi qapanma* ...
1,c74ea36f-6be1-4de4-926d-e117197dcf00,/autos/8475807-lada-vaz-niva-travel,2024-09-13 20:32:19.751157+00,LADA (VAZ) Niva Travel,23700.0,AZN,"Bakı, dünən 23:59",bakı,13.09.2024,23:59,...,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,5,0 km,Tam,Bakı,2cf8b84b-adaf-467a-8f06-3dabcf866c8a,/autos/8475807-lada-vaz-niva-travel,Yüngül lehimli disklər* ABS* Kondisioner* Otur...
2,9cefceb0-024d-4581-a869-a3c2c68a9f95,/autos/8739686-toyota-land-cruiser,2024-09-13 20:32:19.751157+00,Toyota Land Cruiser,35600.0,$,"Bakı, dünən 23:59",bakı,13.09.2024,23:59,...,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,8+,164 750 km,Tam,Bakı,22bb3704-ebe7-4357-ba2f-1806d1a7042b,/autos/8739686-toyota-land-cruiser,Yüngül lehimli disklər* ABS* Lyuk* Mərkəzi qap...
3,459cc337-fb63-48de-9694-41554923d311,/autos/8712597-hyundai-elantra,2024-09-13 20:32:19.751157+00,Hyundai Elantra,26700.0,AZN,"Bakı, dünən 23:59",bakı,13.09.2024,23:59,...,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,NaN,126 000 km,Ön,Bakı,e0d16dac-4091-4417-916e-cadeff600f95,/autos/8712597-hyundai-elantra,Yüngül lehimli disklər* ABS* Lyuk* Yağış senso...
4,6c5ee8d8-1c6f-4fad-a694-957a4c43c25d,/autos/8674773-toyota-prius,2024-09-13 20:32:19.751157+00,Toyota Prius,10500.0,AZN,"Bakı, dünən 23:59",bakı,13.09.2024,23:59,...,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,5,354 000 km,Ön,Bakı,82078856-0d07-4a0d-8123-69c2e5002e07,/autos/8674773-toyota-prius,Arxa görüntü kamerası

In [6]:
#Remove duplicate rows
df.drop_duplicates(inplace=True)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 653721 entries, 0 to 653720
Data columns (total 56 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   id_x                      653721 non-null  str
 1   car_rel_url_x             653721 non-null  str
 2   datetime_scrape           653721 non-null  str
 3   name                      653721 non-null  str
 4   price_x                   653721 non-null  float64
 5   currency_x                653721 non-null  str
 6   datetime_product          653721 non-null  str
 7   city                      653721 non-null  str
 8   day                       653721 non-null  str
 9   hour                      653721 non-null  str
 10  attributes                653721 non-null  str
 11  production_year           653721 non-null  int64
 12  engine_displacement_num   653721 non-null  float64
 13  engine_displacement_unit  647933 non-null  str
 14  kilometrage_num           653721 non-null  int64
 15  kilometrage_unit          647933 non-null  str
 16  barter                    225553 non-null  str
 17  loan                      163340 non-null  str
 18  salon                     193339 non-null  str
 19  spare_parts               1762 non-null    str
 20  vip                       288941 non-null  str
 21  featured                  163835 non-null  str
 22  img_url                   653721 non-null  str
 23  id_y                      653721 non-null  str
 24  cars_id                   653721 non-null  str
 25  car_rel_url_y             653721 non-null  str
 26  datetime                  653721 non-null  str
 27  description               638192 non-null  str
 28  price_y                   653721 non-null  float64
 29  currency_y                653721 non-null  str
 30  owner_name                453496 non-null  str
 31  shop_name                 199960 non-null  str
 32  phone                     653456 non-null  float64
 33  updated                   653721 non-null  str
 34  views                     653721 non-null  int64
 35  vin                       44271 non-null   str
 36  car_details_id_x          653721 non-null  str
 37  Ban növü                  653721 non-null  str
 38  Buraxılış ili             653721 non-null  int64
 39  Hansı bazar üçün yığılıb  464216 non-null  str
 40  Marka                     653721 non-null  str
 41  Model                     653720 non-null  str
 42  Mühərrik                  653721 non-null  str
 43  Qəzalı                    1761 non-null    str
 44  Rəng                      653721 non-null  str
 45  Sahiblər                  432100 non-null  str
 46  Sürətlər qutusu           653721 non-null  str
 47  Vəziyyəti                 653718 non-null  str
 48  Yeni                      653721 non-null  str
 49  Yerlərin sayı             487890 non-null  str
 50  Yürüş                     653721 non-null  str
 51  Ötürücü                   653721 non-null  str
 52  Şəhər                     653721 non-null  str
 53  car_details_id_y          653721 non-null  str
 54  car_rel_url               653721 non-null  str
 55  extra_info                653721 non-null  str
dtypes: float64(4), int64(4), str(48)
memory usage: 279.3 MB

In [8]:
pd.set_option('display.max_columns', None)

In [9]:
df.head()

,id_x,car_rel_url_x,datetime_scrape,name,price_x,currency_x,datetime_product,city,day,hour,attributes,production_year,engine_displacement_num,engine_displacement_unit,kilometrage_num,kilometrage_unit,barter,loan,salon,spare_parts,vip,featured,img_url,id_y,cars_id,car_rel_url_y,datetime,description,price_y,currency_y,owner_name,shop_name,phone,updated,views,vin,car_details_id_x,Ban növü,Buraxılış ili,Hansı bazar üçün yığılıb,Marka,Model,Mühərrik,Qəzalı,Rəng,Sahiblər,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Yürüş,Ötürücü,Şəhər,car_details_id_y,car_rel_url,extra_info
0,3c234145-d57a-4ad6-9448-d43810fc3392,/autos/8748840-hyundai-i30,2024-09-13 20:32:19.751157+00,Hyundai i30,15000.0,AZN,"Bakı, dünən 23:28",bakı,13.09.2024,23:28,"2008, 1.6 L, 270 000 km",2008,1.6,L,270000,km,NaN,NaN,NaN,NaN,NaN,NaN,https://turbo.azstatic.com/uploads/f460x343/20...,8d84d800-fafd-4d5c-b640-f47bd6c5ac20,3c234145-d57a-4ad6-9448-d43810fc3392,/autos/8748840-hyundai-i30,2024-09-13 20:40:28.618345+00,Salam orjinal probeqdir bir ildi bizdedir biri...,15000.0,AZN,Şəmi,NaN,507687355.0,13.09.2024,492,NaN,8d84d800-fafd-4d5c-b640-f47bd6c5ac20,"Hetçbek, 5 qapı",2008,NaN,Hyundai,i30,1.6 L/115 a.g./Dizel,NaN,Gümüşü,2,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,5,270 000 km,Ön,Bakı,8d84d800-fafd-4d5c-b640-f47bd6c5ac20,/autos/8748840-hyundai-i30,Yüngül lehimli disklər* ABS* Mərkəzi qapanma* ...
1,c74ea36f-6be1-4de4-926d-e117197dcf00,/autos/8475807-lada-vaz-niva-travel,2024-09-13 20:32:19.751157+00,LADA (VAZ) Niva Travel,23700.0,AZN,"Bakı, dünən 23:59",bakı,13.09.2024,23:59,"2024, 1.7 L, 0 km",2024,1.7,L,0,km,NaN,NaN,Salon,NaN,vipped-icon,featured-icon,https://turbo.azstatic.com/uploads/f460x343/20...,2cf8b84b-adaf-467a-8f06-3dabcf866c8a,c74ea36f-6be1-4de4-926d-e117197dcf00,/autos/8475807-lada-vaz-niva-travel,2024-09-13 20:40:28.618345+00,LADA Niva Travel modelini nəğd və ya sərfəli l...,23700.0,AZN,NaN,Lada Azərbaycan,554092445.0,13.09.2024,60189,NaN,2cf8b84b-adaf-467a-8f06-3dabcf866c8a,"Offroader / SUV, 5 qapı",2024,Rəsmi diler,LADA (VAZ),Niva Travel,1.7 L/80 a.g./Benzin,NaN,Yaşıl,NaN,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,5,0 km,Tam,Bakı,2cf8b84b-adaf-467a-8f06-3dabcf866c8a,/autos/8475807-lada-vaz-niva-travel,Yüngül lehimli disklər* ABS* Kondisioner* Otur...
2,9cefceb0-024d-4581-a869-a3c2c68a9f95,/autos/8739686-toyota-land-cruiser,2024-09-13 20:32:19.751157+00,Toyota Land Cruiser,35600.0,$,"Bakı, dünən 23:59",bakı,13.09.2024,23:59,"2011, 4.0 L, 164 750 km",2011,4.0,L,164750,km,NaN,NaN,NaN,NaN,vipped-icon,featured-icon,https://turbo.azstatic.com/uploads/f460x343/20...,22bb3704-ebe7-4357-ba2f-1806d1a7042b,9cefceb0-024d-4581-a869-a3c2c68a9f95,/autos/8739686-toyota-land-cruiser,2024-09-13 20:40:28.618345+00,Bezkraska.Mashinda hec bir problem yoxdur.Alve...,35600.0,USD,Anar,NaN,502126242.0,13.09.2024,2473,NaN,22bb3704-ebe7-4357-ba2f-1806d1a7042b,"Offroader / SUV, 5 qapı",2011,Rəsmi diler,Toyota,Land Cruiser,4.0 L/282 a.g./Benzin,NaN,Ağ,0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,8+,164 750 km,Tam,Bakı,22bb3704-ebe7-4357-ba2f-1806d1a7042b,/autos/8739686-toyota-land-cruiser,Yüngül lehimli disklər* ABS* Lyuk* Mərkəzi qap...
3,459cc337-fb63-48de-9694-41554923d311,/autos/8712597-hyundai-elantra,2024-09-13 20:32:19.751157+00,Hyundai Elantra,26700.0,AZN,"Bakı, dünən 23:59",bakı,13.09.2024,23:59,"2018, 2.0 L, 126 000 km",2018,2.0,L,126000,km,NaN,NaN,NaN,NaN,vipped-icon,NaN,https://turbo.azstatic.com/uploads/f460x343/20...,e0d16dac-4091-4417-916e-cadeff600f95,459cc337-fb63-48de-9694-41554923d311,/autos/8712597-hyundai-elantra,2024-09-13 20:40:28.618345+00,2019 alış\n,26700.0,AZN,Babək,NaN,774999004.0,13.09.2024,3727,5NPD84LFXKH406133,e0d16dac-4091-4417-916e-cadeff600f95,Sedan,2018,NaN,Hyundai,Elantra,2.0 L/150 a.g./Benzin,NaN,Boz,1,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,NaN,126 000 km,Ön,Bakı,e0d16dac-4091-4417-916e-cadeff600f95,/autos/8712597-hyundai-elantra,Yüngül lehimli disklər* ABS* Lyuk* Yağış senso...
4,6c5ee8d8-1c6f-4fad-a694-957a4c43c25d,/autos/8674773-toyota-prius,2024-09-13 20:32:19.751157+00,Toyota Prius,10500.0,AZN,"Bakı, dünən 23:59",bakı,13.09.2024,23:59,"2007, 1.5 L, 354 000 km",2007,1.5,L,354000,km,NaN,NaN,NaN,NaN,vipped-icon,NaN,https://turbo.azstatic.com/uploads/f460x343/20...,82078856-0d07-4a0d-8123-69c2e5002e07,6c5ee8d8-1c6f-4fad-a694-957a4c43c25d,/autos/8674773-toyota-prius,2024-09-13 20:40:28.618345+00,"Maşında problem yoxdur. Motor, ABS və batareya...",10500.0,AZN,Natiq,NaN,517264995.0,13.09.2024,446,NaN,82078856-0d07-4a0d-8123-69c2e5002e07,Liftbek,2007,Amerika,Toyota,Prius,1.5 L/76 a.g./Hibrid,NaN,Qırmızı,2,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,5,354 000 km,Ön,Bakı,82078856-0d07-4a0d-8123-69c2e5002e07,/autos/8674773-toyota-prius,Arxa görüntü kamerası

In [10]:
drop = ['id_x', 'car_rel_url_x', 'datetime_scrape', 'datetime_product', 'day', 'hour', 'barter', 'loan', 'salon', 'spare_parts', 'vip', 'featured', 'img_url', 'id_y', 'cars_id', 'car_rel_url_y', 'datetime', 'description', 'owner_name', 'shop_name', 'phone', 'updated', 'vin', 'car_details_id_x', 'Qəzalı', 'car_details_id_y', 'car_rel_url', 'extra_info']

In [11]:
df.drop(columns=drop, inplace=True)

In [12]:
df.head()

,name,price_x,currency_x,city,attributes,production_year,engine_displacement_num,engine_displacement_unit,kilometrage_num,kilometrage_unit,price_y,currency_y,views,Ban növü,Buraxılış ili,Hansı bazar üçün yığılıb,Marka,Model,Mühərrik,Rəng,Sahiblər,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Yürüş,Ötürücü,Şəhər
0,Hyundai i30,15000.0,AZN,bakı,"2008, 1.6 L, 270 000 km",2008,1.6,L,270000,km,15000.0,AZN,492,"Hetçbek, 5 qapı",2008,NaN,Hyundai,i30,1.6 L/115 a.g./Dizel,Gümüşü,2,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,5,270 000 km,Ön,Bakı
1,LADA (VAZ) Niva Travel,23700.0,AZN,bakı,"2024, 1.7 L, 0 km",2024,1.7,L,0,km,23700.0,AZN,60189,"Offroader / SUV, 5 qapı",2024,Rəsmi diler,LADA (VAZ),Niva Travel,1.7 L/80 a.g./Benzin,Yaşıl,NaN,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,5,0 km,Tam,Bakı
2,Toyota Land Cruiser,35600.0,$,bakı,"2011, 4.0 L, 164 750 km",2011,4.0,L,164750,km,35600.0,USD,2473,"Offroader / SUV, 5 qapı",2011,Rəsmi diler,Toyota,Land Cruiser,4.0 L/282 a.g./Benzin,Ağ,0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,8+,164 750 km,Tam,Bakı
3,Hyundai Elantra,26700.0,AZN,bakı,"2018, 2.0 L, 126 000 km",2018,2.0,L,126000,km,26700.0,AZN,3727,Sedan,2018,NaN,Hyundai,Elantra,2.0 L/150 a.g./Benzin,Boz,1,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,NaN,126 000 km,Ön,Bakı
4,Toyota Prius,10500.0,AZN,bakı,"2007, 1.5 L, 354 000 km",2007,1.5,L,354000,km,10500.0,AZN,446,Liftbek,2007,Amerika,Toyota,Prius,1.5 L/76 a.g./Hibrid,Qırmızı,2,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,5,354 000 km,Ön,Bakı

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 653721 entries, 0 to 653720
Data columns (total 28 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   name                      653721 non-null  str
 1   price_x                   653721 non-null  float64
 2   currency_x                653721 non-null  str
 3   city                      653721 non-null  str
 4   attributes                653721 non-null  str
 5   production_year           653721 non-null  int64
 6   engine_displacement_num   653721 non-null  float64
 7   engine_displacement_unit  647933 non-null  str
 8   kilometrage_num           653721 non-null  int64
 9   kilometrage_unit          647933 non-null  str
 10  price_y                   653721 non-null  float64
 11  currency_y                653721 non-null  str
 12  views                     653721 non-null  int64
 13  Ban növü                  653721 non-null  str
 14  Buraxılış ili             653721 non-null  int64
 15  Hansı bazar üçün yığılıb  464216 non-null  str
 16  Marka                     653721 non-null  str
 17  Model                     653720 non-null  str
 18  Mühərrik                  653721 non-null  str
 19  Rəng                      653721 non-null  str
 20  Sahiblər                  432100 non-null  str
 21  Sürətlər qutusu           653721 non-null  str
 22  Vəziyyəti                 653718 non-null  str
 23  Yeni                      653721 non-null  str
 24  Yerlərin sayı             487890 non-null  str
 25  Yürüş                     653721 non-null  str
 26  Ötürücü                   653721 non-null  str
 27  Şəhər                     653721 non-null  str
dtypes: float64(3), int64(4), str(21)
memory usage: 139.6 MB

In [14]:
df.nunique()

name                         2530
price_x                      4323
currency_x                      3
city                           75
attributes                  98227
production_year                73
engine_displacement_num        88
engine_displacement_unit        1
kilometrage_num             33530
kilometrage_unit                1
price_y                      4324
currency_y                      3
views                       33846
Ban növü                       36
Buraxılış ili                  72
Hansı bazar üçün yığılıb        9
Marka                         208
Model                        2451
Mühərrik                     7410
Rəng                           18
Sahiblər                        5
Sürətlər qutusu                 5
Vəziyyəti                       4
Yeni                            2
Yerlərin sayı                   8
Yürüş                       33558
Ötürücü                         3
Şəhər                          75
dtype: int64

In [15]:
dropp = ['engine_displacement_unit', 'kilometrage_unit', 'currency_y', 'price_y', 'Yürüş', 'attributes', 'city', 'views', 'Buraxılış ili']

In [16]:
df.drop(columns=dropp, inplace=True)

In [17]:
df.head()

,name,price_x,currency_x,production_year,engine_displacement_num,kilometrage_num,Ban növü,Hansı bazar üçün yığılıb,Marka,Model,Mühərrik,Rəng,Sahiblər,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Ötürücü,Şəhər
0,Hyundai i30,15000.0,AZN,2008,1.6,270000,"Hetçbek, 5 qapı",NaN,Hyundai,i30,1.6 L/115 a.g./Dizel,Gümüşü,2,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,5,Ön,Bakı
1,LADA (VAZ) Niva Travel,23700.0,AZN,2024,1.7,0,"Offroader / SUV, 5 qapı",Rəsmi diler,LADA (VAZ),Niva Travel,1.7 L/80 a.g./Benzin,Yaşıl,NaN,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,5,Tam,Bakı
2,Toyota Land Cruiser,35600.0,$,2011,4.0,164750,"Offroader / SUV, 5 qapı",Rəsmi diler,Toyota,Land Cruiser,4.0 L/282 a.g./Benzin,Ağ,0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,8+,Tam,Bakı
3,Hyundai Elantra,26700.0,AZN,2018,2.0,126000,Sedan,NaN,Hyundai,Elantra,2.0 L/150 a.g./Benzin,Boz,1,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,NaN,Ön,Bakı
4,Toyota Prius,10500.0,AZN,2007,1.5,354000,Liftbek,Amerika,Toyota,Prius,1.5 L/76 a.g./Hibrid,Qırmızı,2,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,5,Ön,Bakı

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 653721 entries, 0 to 653720
Data columns (total 19 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   name                      653721 non-null  str
 1   price_x                   653721 non-null  float64
 2   currency_x                653721 non-null  str
 3   production_year           653721 non-null  int64
 4   engine_displacement_num   653721 non-null  float64
 5   kilometrage_num           653721 non-null  int64
 6   Ban növü                  653721 non-null  str
 7   Hansı bazar üçün yığılıb  464216 non-null  str
 8   Marka                     653721 non-null  str
 9   Model                     653720 non-null  str
 10  Mühərrik                  653721 non-null  str
 11  Rəng                      653721 non-null  str
 12  Sahiblər                  432100 non-null  str
 13  Sürətlər qutusu           653721 non-null  str
 14  Vəziyyəti                 653718 non-null  str
 15  Yeni                      653721 non-null  str
 16  Yerlərin sayı             487890 non-null  str
 17  Ötürücü                   653721 non-null  str
 18  Şəhər                     653721 non-null  str
dtypes: float64(2), int64(2), str(15)
memory usage: 94.8 MB

In [19]:
#Drop null values in Model column
df.dropna(subset=['Model'], inplace=True)

In [20]:
df.info()

<class 'pandas.DataFrame'>
Index: 653720 entries, 0 to 653720
Data columns (total 19 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   name                      653720 non-null  str
 1   price_x                   653720 non-null  float64
 2   currency_x                653720 non-null  str
 3   production_year           653720 non-null  int64
 4   engine_displacement_num   653720 non-null  float64
 5   kilometrage_num           653720 non-null  int64
 6   Ban növü                  653720 non-null  str
 7   Hansı bazar üçün yığılıb  464215 non-null  str
 8   Marka                     653720 non-null  str
 9   Model                     653720 non-null  str
 10  Mühərrik                  653720 non-null  str
 11  Rəng                      653720 non-null  str
 12  Sahiblər                  432100 non-null  str
 13  Sürətlər qutusu           653720 non-null  str
 14  Vəziyyəti                 653717 non-null  str
 15  Yeni                      653720 non-null  str
 16  Yerlərin sayı             487889 non-null  str
 17  Ötürücü                   653720 non-null  str
 18  Şəhər                     653720 non-null  str
dtypes: float64(2), int64(2), str(15)
memory usage: 99.7 MB

In [21]:
df.info()

<class 'pandas.DataFrame'>
Index: 653720 entries, 0 to 653720
Data columns (total 19 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   name                      653720 non-null  str
 1   price_x                   653720 non-null  float64
 2   currency_x                653720 non-null  str
 3   production_year           653720 non-null  int64
 4   engine_displacement_num   653720 non-null  float64
 5   kilometrage_num           653720 non-null  int64
 6   Ban növü                  653720 non-null  str
 7   Hansı bazar üçün yığılıb  464215 non-null  str
 8   Marka                     653720 non-null  str
 9   Model                     653720 non-null  str
 10  Mühərrik                  653720 non-null  str
 11  Rəng                      653720 non-null  str
 12  Sahiblər                  432100 non-null  str
 13  Sürətlər qutusu           653720 non-null  str
 14  Vəziyyəti                 653717 non-null  str
 15  Yeni                      653720 non-null  str
 16  Yerlərin sayı             487889 non-null  str
 17  Ötürücü                   653720 non-null  str
 18  Şəhər                     653720 non-null  str
dtypes: float64(2), int64(2), str(15)
memory usage: 99.7 MB

In [22]:
df.head()

,name,price_x,currency_x,production_year,engine_displacement_num,kilometrage_num,Ban növü,Hansı bazar üçün yığılıb,Marka,Model,Mühərrik,Rəng,Sahiblər,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Ötürücü,Şəhər
0,Hyundai i30,15000.0,AZN,2008,1.6,270000,"Hetçbek, 5 qapı",NaN,Hyundai,i30,1.6 L/115 a.g./Dizel,Gümüşü,2,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,5,Ön,Bakı
1,LADA (VAZ) Niva Travel,23700.0,AZN,2024,1.7,0,"Offroader / SUV, 5 qapı",Rəsmi diler,LADA (VAZ),Niva Travel,1.7 L/80 a.g./Benzin,Yaşıl,NaN,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,5,Tam,Bakı
2,Toyota Land Cruiser,35600.0,$,2011,4.0,164750,"Offroader / SUV, 5 qapı",Rəsmi diler,Toyota,Land Cruiser,4.0 L/282 a.g./Benzin,Ağ,0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,8+,Tam,Bakı
3,Hyundai Elantra,26700.0,AZN,2018,2.0,126000,Sedan,NaN,Hyundai,Elantra,2.0 L/150 a.g./Benzin,Boz,1,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,NaN,Ön,Bakı
4,Toyota Prius,10500.0,AZN,2007,1.5,354000,Liftbek,Amerika,Toyota,Prius,1.5 L/76 a.g./Hibrid,Qırmızı,2,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,5,Ön,Bakı

In [23]:
df.drop_duplicates(inplace=True)

In [24]:
df.info()

<class 'pandas.DataFrame'>
Index: 223763 entries, 0 to 653720
Data columns (total 19 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   name                      223763 non-null  str
 1   price_x                   223763 non-null  float64
 2   currency_x                223763 non-null  str
 3   production_year           223763 non-null  int64
 4   engine_displacement_num   223763 non-null  float64
 5   kilometrage_num           223763 non-null  int64
 6   Ban növü                  223763 non-null  str
 7   Hansı bazar üçün yığılıb  159918 non-null  str
 8   Marka                     223763 non-null  str
 9   Model                     223763 non-null  str
 10  Mühərrik                  223763 non-null  str
 11  Rəng                      223763 non-null  str
 12  Sahiblər                  157843 non-null  str
 13  Sürətlər qutusu           223763 non-null  str
 14  Vəziyyəti                 223760 non-null  str
 15  Yeni                      223763 non-null  str
 16  Yerlərin sayı             168654 non-null  str
 17  Ötürücü                   223763 non-null  str
 18  Şəhər                     223763 non-null  str
dtypes: float64(2), int64(2), str(15)
memory usage: 34.1 MB

In [25]:
df.nunique()

name                         2529
price_x                      4323
currency_x                      3
production_year                73
engine_displacement_num        88
kilometrage_num             33530
Ban növü                       36
Hansı bazar üçün yığılıb        9
Marka                         208
Model                        2451
Mühərrik                     7409
Rəng                           18
Sahiblər                        5
Sürətlər qutusu                 5
Vəziyyəti                       4
Yeni                            2
Yerlərin sayı                   8
Ötürücü                         3
Şəhər                          75
dtype: int64

In [26]:
df.head()

,name,price_x,currency_x,production_year,engine_displacement_num,kilometrage_num,Ban növü,Hansı bazar üçün yığılıb,Marka,Model,Mühərrik,Rəng,Sahiblər,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Ötürücü,Şəhər
0,Hyundai i30,15000.0,AZN,2008,1.6,270000,"Hetçbek, 5 qapı",NaN,Hyundai,i30,1.6 L/115 a.g./Dizel,Gümüşü,2,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,5,Ön,Bakı
1,LADA (VAZ) Niva Travel,23700.0,AZN,2024,1.7,0,"Offroader / SUV, 5 qapı",Rəsmi diler,LADA (VAZ),Niva Travel,1.7 L/80 a.g./Benzin,Yaşıl,NaN,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,5,Tam,Bakı
2,Toyota Land Cruiser,35600.0,$,2011,4.0,164750,"Offroader / SUV, 5 qapı",Rəsmi diler,Toyota,Land Cruiser,4.0 L/282 a.g./Benzin,Ağ,0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,8+,Tam,Bakı
3,Hyundai Elantra,26700.0,AZN,2018,2.0,126000,Sedan,NaN,Hyundai,Elantra,2.0 L/150 a.g./Benzin,Boz,1,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,NaN,Ön,Bakı
4,Toyota Prius,10500.0,AZN,2007,1.5,354000,Liftbek,Amerika,Toyota,Prius,1.5 L/76 a.g./Hibrid,Qırmızı,2,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,5,Ön,Bakı

In [27]:
df.dropna(subset=['Vəziyyəti'], inplace=True)

In [28]:
df.info()

<class 'pandas.DataFrame'>
Index: 223760 entries, 0 to 653720
Data columns (total 19 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   name                      223760 non-null  str
 1   price_x                   223760 non-null  float64
 2   currency_x                223760 non-null  str
 3   production_year           223760 non-null  int64
 4   engine_displacement_num   223760 non-null  float64
 5   kilometrage_num           223760 non-null  int64
 6   Ban növü                  223760 non-null  str
 7   Hansı bazar üçün yığılıb  159917 non-null  str
 8   Marka                     223760 non-null  str
 9   Model                     223760 non-null  str
 10  Mühərrik                  223760 non-null  str
 11  Rəng                      223760 non-null  str
 12  Sahiblər                  157840 non-null  str
 13  Sürətlər qutusu           223760 non-null  str
 14  Vəziyyəti                 223760 non-null  str
 15  Yeni                      223760 non-null  str
 16  Yerlərin sayı             168654 non-null  str
 17  Ötürücü                   223760 non-null  str
 18  Şəhər                     223760 non-null  str
dtypes: float64(2), int64(2), str(15)
memory usage: 34.1 MB

In [29]:
df['ad'] = df['Marka'] + " " + df['Model']

In [30]:
df.head()

,name,price_x,currency_x,production_year,engine_displacement_num,kilometrage_num,Ban növü,Hansı bazar üçün yığılıb,Marka,Model,Mühərrik,Rəng,Sahiblər,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Ötürücü,Şəhər,ad
0,Hyundai i30,15000.0,AZN,2008,1.6,270000,"Hetçbek, 5 qapı",NaN,Hyundai,i30,1.6 L/115 a.g./Dizel,Gümüşü,2,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,5,Ön,Bakı,Hyundai i30
1,LADA (VAZ) Niva Travel,23700.0,AZN,2024,1.7,0,"Offroader / SUV, 5 qapı",Rəsmi diler,LADA (VAZ),Niva Travel,1.7 L/80 a.g./Benzin,Yaşıl,NaN,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,5,Tam,Bakı,LADA (VAZ) Niva Travel
2,Toyota Land Cruiser,35600.0,$,2011,4.0,164750,"Offroader / SUV, 5 qapı",Rəsmi diler,Toyota,Land Cruiser,4.0 L/282 a.g./Benzin,Ağ,0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,8+,Tam,Bakı,Toyota Land Cruiser
3,Hyundai Elantra,26700.0,AZN,2018,2.0,126000,Sedan,NaN,Hyundai,Elantra,2.0 L/150 a.g./Benzin,Boz,1,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,NaN,Ön,Bakı,Hyundai Elantra
4,Toyota Prius,10500.0,AZN,2007,1.5,354000,Liftbek,Amerika,Toyota,Prius,1.5 L/76 a.g./Hibrid,Qırmızı,2,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,5,Ön,Bakı,Toyota Prius

In [31]:
df.drop(df[df['name'] != df['ad']].index, inplace=True)

In [32]:
df.info()

<class 'pandas.DataFrame'>
Index: 223758 entries, 0 to 653720
Data columns (total 20 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   name                      223758 non-null  str
 1   price_x                   223758 non-null  float64
 2   currency_x                223758 non-null  str
 3   production_year           223758 non-null  int64
 4   engine_displacement_num   223758 non-null  float64
 5   kilometrage_num           223758 non-null  int64
 6   Ban növü                  223758 non-null  str
 7   Hansı bazar üçün yığılıb  159915 non-null  str
 8   Marka                     223758 non-null  str
 9   Model                     223758 non-null  str
 10  Mühərrik                  223758 non-null  str
 11  Rəng                      223758 non-null  str
 12  Sahiblər                  157838 non-null  str
 13  Sürətlər qutusu           223758 non-null  str
 14  Vəziyyəti                 223758 non-null  str
 15  Yeni                      223758 non-null  str
 16  Yerlərin sayı             168652 non-null  str
 17  Ötürücü                   223758 non-null  str
 18  Şəhər                     223758 non-null  str
 19  ad                        223758 non-null  str
dtypes: float64(2), int64(2), str(16)
memory usage: 35.8 MB

In [33]:
df['Hansı bazar üçün yığılıb'].unique()

<StringArray>
[          nan, 'Rəsmi diler',     'Amerika',       'Dubay',      'Rusiya',
         'Çin',      'Avropa',       'Digər',    'Yaponiya',      'Koreya']
Length: 10, dtype: str

In [34]:
df['Hansı bazar üçün yığılıb'] = df['Hansı bazar üçün yığılıb'].fillna(df['Hansı bazar üçün yığılıb'].mode()[0])

In [35]:
df.info()

<class 'pandas.DataFrame'>
Index: 223758 entries, 0 to 653720
Data columns (total 20 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   name                      223758 non-null  str
 1   price_x                   223758 non-null  float64
 2   currency_x                223758 non-null  str
 3   production_year           223758 non-null  int64
 4   engine_displacement_num   223758 non-null  float64
 5   kilometrage_num           223758 non-null  int64
 6   Ban növü                  223758 non-null  str
 7   Hansı bazar üçün yığılıb  223758 non-null  str
 8   Marka                     223758 non-null  str
 9   Model                     223758 non-null  str
 10  Mühərrik                  223758 non-null  str
 11  Rəng                      223758 non-null  str
 12  Sahiblər                  157838 non-null  str
 13  Sürətlər qutusu           223758 non-null  str
 14  Vəziyyəti                 223758 non-null  str
 15  Yeni                      223758 non-null  str
 16  Yerlərin sayı             168652 non-null  str
 17  Ötürücü                   223758 non-null  str
 18  Şəhər                     223758 non-null  str
 19  ad                        223758 non-null  str
dtypes: float64(2), int64(2), str(16)
memory usage: 35.8 MB

In [36]:
df['Sahiblər'].unique()

<StringArray>
['2', nan, '0', '1', '3', '4 və daha çox']
Length: 6, dtype: str

In [37]:
def sahibler(x):
    if x == '4 və daha çox':
        return '4'
    else:
        return x

In [38]:
df['Sahiblər'] = df['Sahiblər'].apply(sahibler)
df['Sahiblər'].unique()

<StringArray>
['2', nan, '0', '1', '3', '4']
Length: 6, dtype: str

In [39]:
df['Sahiblər'] = pd.to_numeric(df['Sahiblər'], errors='coerce')

In [40]:
df.info()

<class 'pandas.DataFrame'>
Index: 223758 entries, 0 to 653720
Data columns (total 20 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   name                      223758 non-null  str
 1   price_x                   223758 non-null  float64
 2   currency_x                223758 non-null  str
 3   production_year           223758 non-null  int64
 4   engine_displacement_num   223758 non-null  float64
 5   kilometrage_num           223758 non-null  int64
 6   Ban növü                  223758 non-null  str
 7   Hansı bazar üçün yığılıb  223758 non-null  str
 8   Marka                     223758 non-null  str
 9   Model                     223758 non-null  str
 10  Mühərrik                  223758 non-null  str
 11  Rəng                      223758 non-null  str
 12  Sahiblər                  157838 non-null  float64
 13  Sürətlər qutusu           223758 non-null  str
 14  Vəziyyəti                 223758 non-null  str
 15  Yeni                      223758 non-null  str
 16  Yerlərin sayı             168652 non-null  str
 17  Ötürücü                   223758 non-null  str
 18  Şəhər                     223758 non-null  str
 19  ad                        223758 non-null  str
dtypes: float64(3), int64(2), str(15)
memory usage: 35.8 MB

In [41]:
df['Sahiblər'] = df['Sahiblər'].fillna(df['Sahiblər'].median())

In [42]:
df.info()

<class 'pandas.DataFrame'>
Index: 223758 entries, 0 to 653720
Data columns (total 20 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   name                      223758 non-null  str
 1   price_x                   223758 non-null  float64
 2   currency_x                223758 non-null  str
 3   production_year           223758 non-null  int64
 4   engine_displacement_num   223758 non-null  float64
 5   kilometrage_num           223758 non-null  int64
 6   Ban növü                  223758 non-null  str
 7   Hansı bazar üçün yığılıb  223758 non-null  str
 8   Marka                     223758 non-null  str
 9   Model                     223758 non-null  str
 10  Mühərrik                  223758 non-null  str
 11  Rəng                      223758 non-null  str
 12  Sahiblər                  223758 non-null  float64
 13  Sürətlər qutusu           223758 non-null  str
 14  Vəziyyəti                 223758 non-null  str
 15  Yeni                      223758 non-null  str
 16  Yerlərin sayı             168652 non-null  str
 17  Ötürücü                   223758 non-null  str
 18  Şəhər                     223758 non-null  str
 19  ad                        223758 non-null  str
dtypes: float64(3), int64(2), str(15)
memory usage: 35.8 MB

In [43]:
df['Yerlərin sayı'].unique()

<StringArray>
['5', '8+', nan, '3', '7', '2', '4', '6', '1']
Length: 9, dtype: str

In [44]:
def yer(x):
    if x == '8+':
        return '8'
    else:
        return x

In [45]:
df['Yerlərin sayı'] = df['Yerlərin sayı'].apply(yer)
df['Yerlərin sayı'].unique()

<StringArray>
['5', '8', nan, '3', '7', '2', '4', '6', '1']
Length: 9, dtype: str

In [46]:
df['Yerlərin sayı']=pd.to_numeric(df['Yerlərin sayı'], errors='coerce')

In [47]:
df['Yerlərin sayı'] = df['Yerlərin sayı'].fillna(df['Yerlərin sayı'].median())

In [48]:
df.info()

<class 'pandas.DataFrame'>
Index: 223758 entries, 0 to 653720
Data columns (total 20 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   name                      223758 non-null  str
 1   price_x                   223758 non-null  float64
 2   currency_x                223758 non-null  str
 3   production_year           223758 non-null  int64
 4   engine_displacement_num   223758 non-null  float64
 5   kilometrage_num           223758 non-null  int64
 6   Ban növü                  223758 non-null  str
 7   Hansı bazar üçün yığılıb  223758 non-null  str
 8   Marka                     223758 non-null  str
 9   Model                     223758 non-null  str
 10  Mühərrik                  223758 non-null  str
 11  Rəng                      223758 non-null  str
 12  Sahiblər                  223758 non-null  float64
 13  Sürətlər qutusu           223758 non-null  str
 14  Vəziyyəti                 223758 non-null  str
 15  Yeni                      223758 non-null  str
 16  Yerlərin sayı             223758 non-null  float64
 17  Ötürücü                   223758 non-null  str
 18  Şəhər                     223758 non-null  str
 19  ad                        223758 non-null  str
dtypes: float64(4), int64(2), str(14)
memory usage: 35.8 MB

In [49]:
df.head()

,name,price_x,currency_x,production_year,engine_displacement_num,kilometrage_num,Ban növü,Hansı bazar üçün yığılıb,Marka,Model,Mühərrik,Rəng,Sahiblər,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Ötürücü,Şəhər,ad
0,Hyundai i30,15000.0,AZN,2008,1.6,270000,"Hetçbek, 5 qapı",Avropa,Hyundai,i30,1.6 L/115 a.g./Dizel,Gümüşü,2.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,Hyundai i30
1,LADA (VAZ) Niva Travel,23700.0,AZN,2024,1.7,0,"Offroader / SUV, 5 qapı",Rəsmi diler,LADA (VAZ),Niva Travel,1.7 L/80 a.g./Benzin,Yaşıl,1.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,5.0,Tam,Bakı,LADA (VAZ) Niva Travel
2,Toyota Land Cruiser,35600.0,$,2011,4.0,164750,"Offroader / SUV, 5 qapı",Rəsmi diler,Toyota,Land Cruiser,4.0 L/282 a.g./Benzin,Ağ,0.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,8.0,Tam,Bakı,Toyota Land Cruiser
3,Hyundai Elantra,26700.0,AZN,2018,2.0,126000,Sedan,Avropa,Hyundai,Elantra,2.0 L/150 a.g./Benzin,Boz,1.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,Hyundai Elantra
4,Toyota Prius,10500.0,AZN,2007,1.5,354000,Liftbek,Amerika,Toyota,Prius,1.5 L/76 a.g./Hibrid,Qırmızı,2.0,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,Toyota Prius

In [50]:
dp = ['Marka', 'Model', 'ad']
df.drop(columns=dp, inplace=True)

In [51]:
df.head()

,name,price_x,currency_x,production_year,engine_displacement_num,kilometrage_num,Ban növü,Hansı bazar üçün yığılıb,Mühərrik,Rəng,Sahiblər,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Ötürücü,Şəhər
0,Hyundai i30,15000.0,AZN,2008,1.6,270000,"Hetçbek, 5 qapı",Avropa,1.6 L/115 a.g./Dizel,Gümüşü,2.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı
1,LADA (VAZ) Niva Travel,23700.0,AZN,2024,1.7,0,"Offroader / SUV, 5 qapı",Rəsmi diler,1.7 L/80 a.g./Benzin,Yaşıl,1.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,5.0,Tam,Bakı
2,Toyota Land Cruiser,35600.0,$,2011,4.0,164750,"Offroader / SUV, 5 qapı",Rəsmi diler,4.0 L/282 a.g./Benzin,Ağ,0.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,8.0,Tam,Bakı
3,Hyundai Elantra,26700.0,AZN,2018,2.0,126000,Sedan,Avropa,2.0 L/150 a.g./Benzin,Boz,1.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı
4,Toyota Prius,10500.0,AZN,2007,1.5,354000,Liftbek,Amerika,1.5 L/76 a.g./Hibrid,Qırmızı,2.0,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı

In [52]:
df['currency_x'].unique()

<StringArray>
['AZN', '$', '€']
Length: 3, dtype: str

In [53]:
exchange_rates = {
    'AZN': 1.00,
    '$':   1.70,
    '€':   1.98
}

df['price_azn'] = df.apply(
    lambda row: row['price_x'] * exchange_rates.get(row['currency_x'], 1.0),
    axis=1
)

In [54]:
df.head()

,name,price_x,currency_x,production_year,engine_displacement_num,kilometrage_num,Ban növü,Hansı bazar üçün yığılıb,Mühərrik,Rəng,Sahiblər,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Ötürücü,Şəhər,price_azn
0,Hyundai i30,15000.0,AZN,2008,1.6,270000,"Hetçbek, 5 qapı",Avropa,1.6 L/115 a.g./Dizel,Gümüşü,2.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,15000.0
1,LADA (VAZ) Niva Travel,23700.0,AZN,2024,1.7,0,"Offroader / SUV, 5 qapı",Rəsmi diler,1.7 L/80 a.g./Benzin,Yaşıl,1.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,5.0,Tam,Bakı,23700.0
2,Toyota Land Cruiser,35600.0,$,2011,4.0,164750,"Offroader / SUV, 5 qapı",Rəsmi diler,4.0 L/282 a.g./Benzin,Ağ,0.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,8.0,Tam,Bakı,60520.0
3,Hyundai Elantra,26700.0,AZN,2018,2.0,126000,Sedan,Avropa,2.0 L/150 a.g./Benzin,Boz,1.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,26700.0
4,Toyota Prius,10500.0,AZN,2007,1.5,354000,Liftbek,Amerika,1.5 L/76 a.g./Hibrid,Qırmızı,2.0,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,10500.0

In [55]:
dp = ['price_x', 'currency_x']
df.drop(columns=dp, inplace=True)

In [56]:
df.head()

,name,production_year,engine_displacement_num,kilometrage_num,Ban növü,Hansı bazar üçün yığılıb,Mühərrik,Rəng,Sahiblər,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Ötürücü,Şəhər,price_azn
0,Hyundai i30,2008,1.6,270000,"Hetçbek, 5 qapı",Avropa,1.6 L/115 a.g./Dizel,Gümüşü,2.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,15000.0
1,LADA (VAZ) Niva Travel,2024,1.7,0,"Offroader / SUV, 5 qapı",Rəsmi diler,1.7 L/80 a.g./Benzin,Yaşıl,1.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,5.0,Tam,Bakı,23700.0
2,Toyota Land Cruiser,2011,4.0,164750,"Offroader / SUV, 5 qapı",Rəsmi diler,4.0 L/282 a.g./Benzin,Ağ,0.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,8.0,Tam,Bakı,60520.0
3,Hyundai Elantra,2018,2.0,126000,Sedan,Avropa,2.0 L/150 a.g./Benzin,Boz,1.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,26700.0
4,Toyota Prius,2007,1.5,354000,Liftbek,Amerika,1.5 L/76 a.g./Hibrid,Qırmızı,2.0,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,10500.0

In [57]:
df['yas'] = 2026 - df['production_year']

In [58]:
df.drop(columns=['production_year'], inplace=True)
df.head()

,name,engine_displacement_num,kilometrage_num,Ban növü,Hansı bazar üçün yığılıb,Mühərrik,Rəng,Sahiblər,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Ötürücü,Şəhər,price_azn,yas
0,Hyundai i30,1.6,270000,"Hetçbek, 5 qapı",Avropa,1.6 L/115 a.g./Dizel,Gümüşü,2.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,15000.0,18
1,LADA (VAZ) Niva Travel,1.7,0,"Offroader / SUV, 5 qapı",Rəsmi diler,1.7 L/80 a.g./Benzin,Yaşıl,1.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,5.0,Tam,Bakı,23700.0,2
2,Toyota Land Cruiser,4.0,164750,"Offroader / SUV, 5 qapı",Rəsmi diler,4.0 L/282 a.g./Benzin,Ağ,0.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,8.0,Tam,Bakı,60520.0,15
3,Hyundai Elantra,2.0,126000,Sedan,Avropa,2.0 L/150 a.g./Benzin,Boz,1.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,26700.0,8
4,Toyota Prius,1.5,354000,Liftbek,Amerika,1.5 L/76 a.g./Hibrid,Qırmızı,2.0,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,10500.0,19

In [59]:
df['at_gucu'] = df['Mühərrik'].str.split('/').str[1].str.extract('(\d+)')[0]
df['at_gucu'] = pd.to_numeric(df['at_gucu'], errors='coerce')

df.head()

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
/var/folders/hy/n420tyvd6m54vsvk843qjrbc0000gn/T/ipykernel_25438/2903336859.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  df['at_gucu'] = df['Mühərrik'].str.split('/').str[1].str.extract('(\d+)')[0]

,name,engine_displacement_num,kilometrage_num,Ban növü,Hansı bazar üçün yığılıb,Mühərrik,Rəng,Sahiblər,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Ötürücü,Şəhər,price_azn,yas,at_gucu
0,Hyundai i30,1.6,270000,"Hetçbek, 5 qapı",Avropa,1.6 L/115 a.g./Dizel,Gümüşü,2.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,15000.0,18,115.0
1,LADA (VAZ) Niva Travel,1.7,0,"Offroader / SUV, 5 qapı",Rəsmi diler,1.7 L/80 a.g./Benzin,Yaşıl,1.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,5.0,Tam,Bakı,23700.0,2,80.0
2,Toyota Land Cruiser,4.0,164750,"Offroader / SUV, 5 qapı",Rəsmi diler,4.0 L/282 a.g./Benzin,Ağ,0.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,8.0,Tam,Bakı,60520.0,15,282.0
3,Hyundai Elantra,2.0,126000,Sedan,Avropa,2.0 L/150 a.g./Benzin,Boz,1.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,26700.0,8,150.0
4,Toyota Prius,1.5,354000,Liftbek,Amerika,1.5 L/76 a.g./Hibrid,Qırmızı,2.0,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,10500.0,19,76.0

In [60]:
df.info()

<class 'pandas.DataFrame'>
Index: 223758 entries, 0 to 653720
Data columns (total 17 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   name                      223758 non-null  str
 1   engine_displacement_num   223758 non-null  float64
 2   kilometrage_num           223758 non-null  int64
 3   Ban növü                  223758 non-null  str
 4   Hansı bazar üçün yığılıb  223758 non-null  str
 5   Mühərrik                  223758 non-null  str
 6   Rəng                      223758 non-null  str
 7   Sahiblər                  223758 non-null  float64
 8   Sürətlər qutusu           223758 non-null  str
 9   Vəziyyəti                 223758 non-null  str
 10  Yeni                      223758 non-null  str
 11  Yerlərin sayı             223758 non-null  float64
 12  Ötürücü                   223758 non-null  str
 13  Şəhər                     223758 non-null  str
 14  price_azn                 223758 non-null  float64
 15  yas                       223758 non-null  int64
 16  at_gucu                   222611 non-null  float64
dtypes: float64(5), int64(2), str(10)
memory usage: 30.7 MB

In [61]:
df['at_gucu']=df['at_gucu'].fillna(df['at_gucu'].median())

In [62]:
df.info()

<class 'pandas.DataFrame'>
Index: 223758 entries, 0 to 653720
Data columns (total 17 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   name                      223758 non-null  str
 1   engine_displacement_num   223758 non-null  float64
 2   kilometrage_num           223758 non-null  int64
 3   Ban növü                  223758 non-null  str
 4   Hansı bazar üçün yığılıb  223758 non-null  str
 5   Mühərrik                  223758 non-null  str
 6   Rəng                      223758 non-null  str
 7   Sahiblər                  223758 non-null  float64
 8   Sürətlər qutusu           223758 non-null  str
 9   Vəziyyəti                 223758 non-null  str
 10  Yeni                      223758 non-null  str
 11  Yerlərin sayı             223758 non-null  float64
 12  Ötürücü                   223758 non-null  str
 13  Şəhər                     223758 non-null  str
 14  price_azn                 223758 non-null  float64
 15  yas                       223758 non-null  int64
 16  at_gucu                   223758 non-null  float64
dtypes: float64(5), int64(2), str(10)
memory usage: 30.7 MB

In [63]:
df.head()

,name,engine_displacement_num,kilometrage_num,Ban növü,Hansı bazar üçün yığılıb,Mühərrik,Rəng,Sahiblər,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Ötürücü,Şəhər,price_azn,yas,at_gucu
0,Hyundai i30,1.6,270000,"Hetçbek, 5 qapı",Avropa,1.6 L/115 a.g./Dizel,Gümüşü,2.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,15000.0,18,115.0
1,LADA (VAZ) Niva Travel,1.7,0,"Offroader / SUV, 5 qapı",Rəsmi diler,1.7 L/80 a.g./Benzin,Yaşıl,1.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,5.0,Tam,Bakı,23700.0,2,80.0
2,Toyota Land Cruiser,4.0,164750,"Offroader / SUV, 5 qapı",Rəsmi diler,4.0 L/282 a.g./Benzin,Ağ,0.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,8.0,Tam,Bakı,60520.0,15,282.0
3,Hyundai Elantra,2.0,126000,Sedan,Avropa,2.0 L/150 a.g./Benzin,Boz,1.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,26700.0,8,150.0
4,Toyota Prius,1.5,354000,Liftbek,Amerika,1.5 L/76 a.g./Hibrid,Qırmızı,2.0,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,10500.0,19,76.0

In [64]:
df['Yanacaq'] = df['Mühərrik'].str.split('/').str[2]

df.head()

,name,engine_displacement_num,kilometrage_num,Ban növü,Hansı bazar üçün yığılıb,Mühərrik,Rəng,Sahiblər,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Ötürücü,Şəhər,price_azn,yas,at_gucu,Yanacaq
0,Hyundai i30,1.6,270000,"Hetçbek, 5 qapı",Avropa,1.6 L/115 a.g./Dizel,Gümüşü,2.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,15000.0,18,115.0,Dizel
1,LADA (VAZ) Niva Travel,1.7,0,"Offroader / SUV, 5 qapı",Rəsmi diler,1.7 L/80 a.g./Benzin,Yaşıl,1.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,5.0,Tam,Bakı,23700.0,2,80.0,Benzin
2,Toyota Land Cruiser,4.0,164750,"Offroader / SUV, 5 qapı",Rəsmi diler,4.0 L/282 a.g./Benzin,Ağ,0.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,8.0,Tam,Bakı,60520.0,15,282.0,Benzin
3,Hyundai Elantra,2.0,126000,Sedan,Avropa,2.0 L/150 a.g./Benzin,Boz,1.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,26700.0,8,150.0,Benzin
4,Toyota Prius,1.5,354000,Liftbek,Amerika,1.5 L/76 a.g./Hibrid,Qırmızı,2.0,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,10500.0,19,76.0,Hibrid

In [65]:
df.info()

<class 'pandas.DataFrame'>
Index: 223758 entries, 0 to 653720
Data columns (total 18 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   name                      223758 non-null  str
 1   engine_displacement_num   223758 non-null  float64
 2   kilometrage_num           223758 non-null  int64
 3   Ban növü                  223758 non-null  str
 4   Hansı bazar üçün yığılıb  223758 non-null  str
 5   Mühərrik                  223758 non-null  str
 6   Rəng                      223758 non-null  str
 7   Sahiblər                  223758 non-null  float64
 8   Sürətlər qutusu           223758 non-null  str
 9   Vəziyyəti                 223758 non-null  str
 10  Yeni                      223758 non-null  str
 11  Yerlərin sayı             223758 non-null  float64
 12  Ötürücü                   223758 non-null  str
 13  Şəhər                     223758 non-null  str
 14  price_azn                 223758 non-null  float64
 15  yas                       223758 non-null  int64
 16  at_gucu                   223758 non-null  float64
 17  Yanacaq                   222611 non-null  object
dtypes: float64(5), int64(2), object(1), str(10)
memory usage: 32.4+ MB

In [66]:
df['Yanacaq'].unique()

array(['Dizel', 'Benzin', 'Hibrid', 'Elektro', 'Plug-in Hibrid', 'Qaz',
       'Hidrogen', ' Benzin', ' Dizel', nan, ' Plug-in Hibrid', ' Hibrid',
       ' Qaz', ' Hidrogen'], dtype=object)

In [67]:
df['Yanacaq'] = df['Yanacaq'].str.strip()

In [68]:
df['Yanacaq'].unique()

array(['Dizel', 'Benzin', 'Hibrid', 'Elektro', 'Plug-in Hibrid', 'Qaz',
       'Hidrogen', nan], dtype=object)

In [69]:
df['Yanacaq'] = df['Yanacaq'].fillna(df['Yanacaq'].mode()[0])

In [70]:
df.info()

<class 'pandas.DataFrame'>
Index: 223758 entries, 0 to 653720
Data columns (total 18 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   name                      223758 non-null  str
 1   engine_displacement_num   223758 non-null  float64
 2   kilometrage_num           223758 non-null  int64
 3   Ban növü                  223758 non-null  str
 4   Hansı bazar üçün yığılıb  223758 non-null  str
 5   Mühərrik                  223758 non-null  str
 6   Rəng                      223758 non-null  str
 7   Sahiblər                  223758 non-null  float64
 8   Sürətlər qutusu           223758 non-null  str
 9   Vəziyyəti                 223758 non-null  str
 10  Yeni                      223758 non-null  str
 11  Yerlərin sayı             223758 non-null  float64
 12  Ötürücü                   223758 non-null  str
 13  Şəhər                     223758 non-null  str
 14  price_azn                 223758 non-null  float64
 15  yas                       223758 non-null  int64
 16  at_gucu                   223758 non-null  float64
 17  Yanacaq                   223758 non-null  object
dtypes: float64(5), int64(2), object(1), str(10)
memory usage: 32.4+ MB

In [71]:
df.head()

,name,engine_displacement_num,kilometrage_num,Ban növü,Hansı bazar üçün yığılıb,Mühərrik,Rəng,Sahiblər,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Ötürücü,Şəhər,price_azn,yas,at_gucu,Yanacaq
0,Hyundai i30,1.6,270000,"Hetçbek, 5 qapı",Avropa,1.6 L/115 a.g./Dizel,Gümüşü,2.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,15000.0,18,115.0,Dizel
1,LADA (VAZ) Niva Travel,1.7,0,"Offroader / SUV, 5 qapı",Rəsmi diler,1.7 L/80 a.g./Benzin,Yaşıl,1.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,5.0,Tam,Bakı,23700.0,2,80.0,Benzin
2,Toyota Land Cruiser,4.0,164750,"Offroader / SUV, 5 qapı",Rəsmi diler,4.0 L/282 a.g./Benzin,Ağ,0.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,8.0,Tam,Bakı,60520.0,15,282.0,Benzin
3,Hyundai Elantra,2.0,126000,Sedan,Avropa,2.0 L/150 a.g./Benzin,Boz,1.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,26700.0,8,150.0,Benzin
4,Toyota Prius,1.5,354000,Liftbek,Amerika,1.5 L/76 a.g./Hibrid,Qırmızı,2.0,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,10500.0,19,76.0,Hibrid

In [72]:
df.drop(columns = ['Mühərrik'], inplace=True)

In [73]:
df.head()

,name,engine_displacement_num,kilometrage_num,Ban növü,Hansı bazar üçün yığılıb,Rəng,Sahiblər,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Ötürücü,Şəhər,price_azn,yas,at_gucu,Yanacaq
0,Hyundai i30,1.6,270000,"Hetçbek, 5 qapı",Avropa,Gümüşü,2.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,15000.0,18,115.0,Dizel
1,LADA (VAZ) Niva Travel,1.7,0,"Offroader / SUV, 5 qapı",Rəsmi diler,Yaşıl,1.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,5.0,Tam,Bakı,23700.0,2,80.0,Benzin
2,Toyota Land Cruiser,4.0,164750,"Offroader / SUV, 5 qapı",Rəsmi diler,Ağ,0.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,8.0,Tam,Bakı,60520.0,15,282.0,Benzin
3,Hyundai Elantra,2.0,126000,Sedan,Avropa,Boz,1.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,26700.0,8,150.0,Benzin
4,Toyota Prius,1.5,354000,Liftbek,Amerika,Qırmızı,2.0,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,10500.0,19,76.0,Hibrid

In [74]:
df.info()

<class 'pandas.DataFrame'>
Index: 223758 entries, 0 to 653720
Data columns (total 17 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   name                      223758 non-null  str
 1   engine_displacement_num   223758 non-null  float64
 2   kilometrage_num           223758 non-null  int64
 3   Ban növü                  223758 non-null  str
 4   Hansı bazar üçün yığılıb  223758 non-null  str
 5   Rəng                      223758 non-null  str
 6   Sahiblər                  223758 non-null  float64
 7   Sürətlər qutusu           223758 non-null  str
 8   Vəziyyəti                 223758 non-null  str
 9   Yeni                      223758 non-null  str
 10  Yerlərin sayı             223758 non-null  float64
 11  Ötürücü                   223758 non-null  str
 12  Şəhər                     223758 non-null  str
 13  price_azn                 223758 non-null  float64
 14  yas                       223758 non-null  int64
 15  at_gucu                   223758 non-null  float64
 16  Yanacaq                   223758 non-null  object
dtypes: float64(5), int64(2), object(1), str(9)
memory usage: 30.7+ MB

In [75]:
df.nunique()

name                         2529
engine_displacement_num        88
kilometrage_num             33530
Ban növü                       36
Hansı bazar üçün yığılıb        9
Rəng                           18
Sahiblər                        5
Sürətlər qutusu                 5
Vəziyyəti                       4
Yeni                            2
Yerlərin sayı                   8
Ötürücü                         3
Şəhər                          75
price_azn                    5417
yas                            73
at_gucu                       588
Yanacaq                         7
dtype: int64

In [76]:
df['Şəhər'].unique()

<StringArray>
[        'Bakı',     'Sumqayıt',    'Biləsuvar',      'Balakən',
      'Masallı',       'Şəmkir',        'Ağdaş',        'Tovuz',
       'Şabran',        'Gəncə',       'Yevlax',        'Qusar',
       'Şirvan',         'Şəki',       'İmişli',     'Ağcabədi',
       'Göygöl',     'Kürdəmir',       'Salyan',         'Quba',
     'Lənkəran',      'Siyəzən',     'Xırdalan',     'Beyləqan',
       'Qəbələ',     'Yardımlı',       'Xaçmaz',     'Zaqatala',
   'Mingəçevir',    'İsmayıllı',        'Qazax',        'Samux',
       'Tərtər',        'Bərdə',       'Göyçay',         'Ağsu',
    'Sabirabad',      'Gədəbəy',    'Cəlilabad',         'Oğuz',
       'Şamaxı',         'Ucar',       'Astara',          'Qax',
       'Saatlı',     'Naxçıvan',     'Goranboy',       'Zərdab',
        'Babək',     'Neftçala',        'Xudat',      'Ağstafa',
        'Ağdam',     'Xankəndi',     'Cəbrayıl',    'Hacıqabul',
     'Qobustan',       'Füzuli',        'Lerik',      'Göytəpə',
      'Ordubad',     'Daşkəsən',         'Xızı', 'Dəliməmmədli',
     'Naftalan',      'Horadiz',        'Şərur',        'Laçın',
        'Culfa',       'Xocalı',     'Zəngilan',        'Liman',
         'Şuşa',       'Ağdərə',      'Qubadlı']
Length: 75, dtype: str

In [77]:
df['Vəziyyəti'].value_counts()

Vəziyyəti
Vuruğu yoxdur, rənglənməyib    204091
Vuruğu yoxdur, rənglənib        15983
Vuruğu var, rənglənib            1975
Vuruğu var, rənglənməyib         1709
Name: count, dtype: int64

In [78]:
df.head()

,name,engine_displacement_num,kilometrage_num,Ban növü,Hansı bazar üçün yığılıb,Rəng,Sahiblər,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Ötürücü,Şəhər,price_azn,yas,at_gucu,Yanacaq
0,Hyundai i30,1.6,270000,"Hetçbek, 5 qapı",Avropa,Gümüşü,2.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,15000.0,18,115.0,Dizel
1,LADA (VAZ) Niva Travel,1.7,0,"Offroader / SUV, 5 qapı",Rəsmi diler,Yaşıl,1.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,5.0,Tam,Bakı,23700.0,2,80.0,Benzin
2,Toyota Land Cruiser,4.0,164750,"Offroader / SUV, 5 qapı",Rəsmi diler,Ağ,0.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,8.0,Tam,Bakı,60520.0,15,282.0,Benzin
3,Hyundai Elantra,2.0,126000,Sedan,Avropa,Boz,1.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,26700.0,8,150.0,Benzin
4,Toyota Prius,1.5,354000,Liftbek,Amerika,Qırmızı,2.0,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,10500.0,19,76.0,Hibrid

In [79]:
price = df['price_azn']
df.drop(columns=['price_azn'], inplace=True)
df['price_azn'] = price

In [80]:
df.head()

,name,engine_displacement_num,kilometrage_num,Ban növü,Hansı bazar üçün yığılıb,Rəng,Sahiblər,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Ötürücü,Şəhər,yas,at_gucu,Yanacaq,price_azn
0,Hyundai i30,1.6,270000,"Hetçbek, 5 qapı",Avropa,Gümüşü,2.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,18,115.0,Dizel,15000.0
1,LADA (VAZ) Niva Travel,1.7,0,"Offroader / SUV, 5 qapı",Rəsmi diler,Yaşıl,1.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,5.0,Tam,Bakı,2,80.0,Benzin,23700.0
2,Toyota Land Cruiser,4.0,164750,"Offroader / SUV, 5 qapı",Rəsmi diler,Ağ,0.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,8.0,Tam,Bakı,15,282.0,Benzin,60520.0
3,Hyundai Elantra,2.0,126000,Sedan,Avropa,Boz,1.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,8,150.0,Benzin,26700.0
4,Toyota Prius,1.5,354000,Liftbek,Amerika,Qırmızı,2.0,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,19,76.0,Hibrid,10500.0

In [81]:
df.rename(columns={
    'engine_displacement_num': 'motor',
    'kilometrage_num': 'probeg',
    'name': 'ad'
}, inplace=True)

df.head()

,ad,motor,probeg,Ban növü,Hansı bazar üçün yığılıb,Rəng,Sahiblər,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Ötürücü,Şəhər,yas,at_gucu,Yanacaq,price_azn
0,Hyundai i30,1.6,270000,"Hetçbek, 5 qapı",Avropa,Gümüşü,2.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,18,115.0,Dizel,15000.0
1,LADA (VAZ) Niva Travel,1.7,0,"Offroader / SUV, 5 qapı",Rəsmi diler,Yaşıl,1.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,5.0,Tam,Bakı,2,80.0,Benzin,23700.0
2,Toyota Land Cruiser,4.0,164750,"Offroader / SUV, 5 qapı",Rəsmi diler,Ağ,0.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,8.0,Tam,Bakı,15,282.0,Benzin,60520.0
3,Hyundai Elantra,2.0,126000,Sedan,Avropa,Boz,1.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,8,150.0,Benzin,26700.0
4,Toyota Prius,1.5,354000,Liftbek,Amerika,Qırmızı,2.0,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,19,76.0,Hibrid,10500.0

In [82]:
df.head()

,ad,motor,probeg,Ban növü,Hansı bazar üçün yığılıb,Rəng,Sahiblər,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Ötürücü,Şəhər,yas,at_gucu,Yanacaq,price_azn
0,Hyundai i30,1.6,270000,"Hetçbek, 5 qapı",Avropa,Gümüşü,2.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,18,115.0,Dizel,15000.0
1,LADA (VAZ) Niva Travel,1.7,0,"Offroader / SUV, 5 qapı",Rəsmi diler,Yaşıl,1.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,5.0,Tam,Bakı,2,80.0,Benzin,23700.0
2,Toyota Land Cruiser,4.0,164750,"Offroader / SUV, 5 qapı",Rəsmi diler,Ağ,0.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,8.0,Tam,Bakı,15,282.0,Benzin,60520.0
3,Hyundai Elantra,2.0,126000,Sedan,Avropa,Boz,1.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,8,150.0,Benzin,26700.0
4,Toyota Prius,1.5,354000,Liftbek,Amerika,Qırmızı,2.0,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,5.0,Ön,Bakı,19,76.0,Hibrid,10500.0

In [83]:
df['Ban növü'].unique()

<StringArray>
[        'Hetçbek, 5 qapı', 'Offroader / SUV, 5 qapı',
                   'Sedan',                 'Liftbek',
              'Yük maşını',             'Kompakt-Van',
                  'Furqon',                 'Minivan',
            'Mikroavtobus',       'Universal, 5 qapı',
              'Motosiklet', 'Offroader / SUV, 3 qapı',
                'SUV Kupe',                    'Kupe',
     'Pikap, ikiqat kabin',         'Hetçbek, 3 qapı',
         'Hetçbek, 4 qapı',                  'Dartqı',
               'Kabriolet',              'Kvadrosikl',
                 'Limuzin',       'Universal, 3 qapı',
                 'Avtobus',                 'Rodster',
   'Offroader / SUV, açıq',                   'Moped',
        'Pikap, tək kabin',                  'Karvan',
                     'Van',                'Mikrovan',
  'Pikap, bir yarım kabin',                   'Tarqa',
                 'Fastbek',                  'Fayton',
                'Spidster',                 'Qolfkar']
Length: 36, dtype: str

In [84]:
df.to_csv('cleaned_data.csv', index=False)